// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

console.log("Supabase config:", {
  URL: SUPABASE_URL,
  KEY: SUPABASE_PUBLISHABLE_KEY ? "***present***" : "***MISSING***"
});

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("❌ Supabase credentials are missing! Check .env or .env.local");
}

if (SUPABASE_PUBLISHABLE_KEY && !SUPABASE_PUBLISHABLE_KEY.startsWith("eyJ")) {
  console.error(
    "❌ VITE_SUPABASE_PUBLISHABLE_KEY does not look like a valid Supabase anon key (expected a JWT starting with 'eyJ'). " +
    "Check your .env and .env.local files — .env.local takes priority and may be overriding the correct key."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  },
  global: {
    headers: {
      'X-Client-Info': 'health-zenith-shield',
    },
    fetch: async (url, options = {}) => {
      console.log('Supabase fetch:', url);
      try {
        const response = await fetch(url, {
          ...options,
          signal: AbortSignal.timeout(30000), // 30 second timeout
        });
        return response;
      } catch (error) {
        console.error('Fetch error:', error);
        throw error;
      }
    },
  },
});